### ISSUE TITLE
Error while setting up platform hf_weather

### ISSUE THREAD

**Issue by lingxide** [cnk700i/ha_modified_components#12]
Error while setting up platform hf_weather
Traceback (most recent call last):
  File "/home/homeassistant/.local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/home/homeassistant/.homeassistant/custom_components/hf_weather/weather.py", line 86, in async_setup_platform
    yield from data.async_update(dt_util.now())
  File "/home/homeassistant/.homeassistant/custom_components/hf_weather/weather.py", line 407, in async_update
    [forec_cond[6], int(datemsg[6]["tmp"]["max"]), int(datemsg[6]["tmp"]["min"]), datemsg[6]["date"], datemsg[6]["pcpn"], datemsg[6]["pop"]]
IndexError: list index out of range

arch | armv7l- | --
dev | false
docker | false
hassio | false
os_name | Linux
python_version | 3.7.3
timezone | Asia/Shanghai
version | 0.102.3
virtualenv | false

May I have your reply on this?

**Comment by lingxide** [comment]
Resolved, line 46:

```
'rainy': ["毛毛雨", "小雨", "**小到中雨**", "中雨", "大雨", "阵雨", "极端降雨"],
```
